site_name: 引き継ぎ資料(Handover Information)
pages:
    - index.md
    - research_abst.md
    - program.md
    - my_robo.md
    - other.md
theme:
    name: material
    feature:
        tabs: true
    language: 'ja'
extra:
    font:
        text: "Noto Sans JP"
        code: "Consolas"
    palette:
        primary: "indigo"
        accent: "red"
    search:
        language: 'jp'
extra_css:
    - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
markdown_extensions:
    - mdx_math
    - admonition
    - fontawesome_markdown
    - pymdownx.emoji
    - def_list
    - pymdownx.smartsymbols
    - pymdownx.keys
    - codehilite
    - footnotes
extra_javascript: 
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
